### ISSUE TITLE
How do we set additional headers?

### ISSUE THREAD

**Issue by jamieburchell** [DaveRandom/Resume#5]
Looking at the code and examples and I can't see how I could set additional headers for cache control. It's not possible to extend the Servlet class and overwrite the default headers method as the class is final.

**Comment by DaveRandom** [comment]
As referenced in my response to #6, this would need a custom `Resource` implementation, specifically the [`getAdditionalHeaders()`](https://github.com/DaveRandom/Resume/blob/master/src/Resource.php#L30-L35) method.

I will close this issue in favour of #6 because they are closely related, and I think it will be more helpful to talk about specifics if there are any follow-ups :-)
